stages:
  - test
  - build
  - deploy
  - check
before_script:
  - apk --no-cache add curl gettext
check-markdown:
  image: gouvinb/docker-markdownlint
  stage: test
  script: markdownlint content/

build:
  image: tnwhitwell/docker-hugo-builder:0.40
  services:
    - docker:dind
  stage: build
  script:
    - export DOCKER_HOST="tcp://localhost:2375"
    - docker version
    - docker login -u gitlab-ci-token -p "$CI_BUILD_TOKEN" "$CI_REGISTRY"
    - hugo -b "https://whi.tw/ell" -d public
    - hugo -b "https://whi.tw/ell/amp" --config amp.toml -d public/amp
    - docker build --pull -t "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}" .
    - docker push "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}"
  variables:
    GIT_SUBMODULE_STRATEGY: recursive

k8s-deploy-dev:
  image: tnwhitwell/docker-kubectl:v1.10.0
  services:
    - docker:dind
  stage: deploy
  script:
    - kubectl config set-cluster my-cluster --server="${K8S_DEPLOY_URL}" --insecure-skip-tls-verify=true
    - kubectl config set-credentials admin --token="${K8S_DEPLOY_TOKEN}"
    - kubectl config set-context default-context --cluster=my-cluster --user=admin
    - kubectl config use-context default-context
    - /bin/sh deploy/deploy.sh ${CI_REGISTRY_IMAGE} ${CI_COMMIT_SHA} dev dev.whi.tw
  environment:
    name: dev
    url: https://dev.whi.tw/ell
  only:
    - develop
    - master

k8s-deploy-prod:
  image: tnwhitwell/docker-kubectl:v1.10.0
  services:
    - docker:dind
  stage: deploy
  script:
    - kubectl config set-cluster my-cluster --server="${K8S_DEPLOY_URL}" --insecure-skip-tls-verify=true
    - kubectl config set-credentials admin --token="${K8S_DEPLOY_TOKEN}"
    - kubectl config set-context default-context --cluster=my-cluster --user=admin
    - kubectl config use-context default-context
    - /bin/sh deploy/deploy.sh ${CI_REGISTRY_IMAGE} ${CI_COMMIT_SHA} prod whi.tw
  environment:
    name: prod
    url: https://whi.tw/ell
  only:
    - master

check-deploy-finished:
  image: tnwhitwell/docker-kubectl:v1.10.0
  stage: check
  script:
    - while ! kubectl rollout status deployment/my-website-${CI_ENVIRONMENT_NAME} -n my-website-${CI_ENVIRONMENT_NAME}; do sleep 1; done
  only:
    - master
    - develop

