baseURL = "https://indev.whitwell.xyz/"
languageCode = "en-gb"
title = "Tom Whitwell"
theme = "cactus"
uglyURLs = true
# Theme Parameters
[params]
    name = "Tom Whitwell"
    description = "Tom Whitwell's personal website"
    bio = "Linux SysAdmin / DevOps in training"
    twitter = "tnwhitwell"
    enableRSS = true
    iconFont = "mono-social"

# Social Links
[social]
    github = "https://github.com/tnwhitwell"
    twitter = "https://twitter.com/tnwhitwell"
    linkedin = "https://www.linkedin.com/in/tnwhitwell/"
    keybase = "https://keybase.io/tnwhitwell"

# Menu Links
[[menu.main]]
    name = "Blog"
    weight = 1
    url = "/posts/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"