baseURL = "https://indev.whitwell.xyz/"
languageCode = "en-gb"
title = "Tom Whitwell"
theme = "nix"
disqusShortname = "tom-whitwell-xyz"

# Menu Links
[menu]
    [[menu.header]]
        name = "Posts"
        weight = 1
        url = "/posts/"
    [[menu.header]]
        name = "About"
        weight = 0
        url = "/about/"

# Theme Parameters
[params]
    GnuPGFingerprint = "2FF4C64C9183D2FE"
    #StackExchangeID = "your_stackexchange_id"
    #StackOverflowID = "your_stackoverflow_id"
    GithubID = "tnwhitwell"
    #GitlabId = "your_gitlab"
    #BitbucketID = "your_bitbucket_id"
    TwitterID = "tnwhitwell"
    #CodepenID = "your_codepen"
    LinkedInID = "tnwhitwell"
    #GoogleplusID = "your_googleplus"
    #FacebookID = "your_facebook"
    #InstagramID = "your_instagram"
    #TelegramID = "your_telegram"
    Name = "Tom Whitwell"
    HeaderUsername = "tnwhitwell"
    HeaderHostname = "ip-78-31-111-75"
    Email = "hi@whitwell.xyz"
    #Phone = "+1-201-555-0123"
    #Mobile = "+1-201-555-0123"
    About = "Linux SysAdmin / DevOps in training"
    #ProfilePicture = "profile_picture_url"
    #SlackURL = "https://join.slack.com/..."
    GoogleAnalytics = "UA-51691857-1"
    PayPalMeID = "tnwhitwell"
    #XingURL = "https://www.xing.com/profile/..."
