[build]
    publish = "build/"
    command = "make HEADER_ENV=netlify"

[build.environment]
    HUGO_VERSION = "0.53"

[context.production.environment]
    HUGO_ENV = "production"
    HUGO_ENABLEGITINFO = "false"

[context.deploy-preview.environment]
    HUGO_ENV = "development"
    HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "/"
  to = "/ell"
