[build]
    publish = "build/"
    command = "make HEADER_ENV=netlify"
[context.production]
[context.production.environment]
    HUGO_VERSION = "0.53"
    HUGO_ENV = "production"
    HUGO_ENABLEGITINFO = "true"


[[redirects]]
  from = "/"
  to = "/ell"
