apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: my-website-${NAMESPACE}
  labels:
    app: my-website-${NAMESPACE}
  namespace: my-website-${NAMESPACE}
spec:
  replicas: 4
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: my-website-${NAMESPACE}
      tier: frontend
  template:
    metadata:
      labels:
        app: my-website-${NAMESPACE}
        tier: frontend
      namespace: my-website-${NAMESPACE}
    spec:
      imagePullSecrets:
      - name: my-gitlab
      containers:
      - name: my-website-${NAMESPACE}
        imagePullPolicy: Always
        image: ${REGISTRY}:${BUILD_NUMBER}
        resources:
          requests:
            cpu: 500m
        ports:
        - containerPort: 80
          name: my-website-${NAMESPACE}
        env:
        - name: ENVIRONMENT
          value: ${NAMESPACE}
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /about
            port: 80
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 2
          successThreshold: 1
          timeoutSeconds: 1