---
platform: linux

image_resource:
  type: docker-image
  source: {repository: tnwhitwell/docker-hugo-builder}

inputs:
  - name: website_source

run:
  path: ./website_source/ci/scripts/build_with_hugo.sh
