replicaCount: 2

ingress:
  enabled: true
  annotations:
    kubernetes.io/tls-acme: "true"
    certmanager.k8s.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  path: /
  hosts:
    - whi.tw
  tls:
   - secretName: my-website-tls
     hosts:
       - whi.tw
