baseURL = "https://whi.tw/ell/"
googleAnalytics = "UA-51691857-1"
theme = "cocoa-eh"
canonifyurls = true
contentdir = "content"
languageCode = "en-GB"
layoutdir = "layouts"
publishdir = "public"
author = "Tom Whitwell"
title = "Tom Whitwell"
pluralizelisttitles = false

disableKinds = ["taxonomy", "taxonomyTerm"]

# Theme Parameters
[params]
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "My Blog"
copyright = "Copyright © 2017-{year} Tom Whitwell"
copyrightUrl = "https://creativecommons.org/licenses/by-sa/4.0/"
logofile = ""
highlightjs = true
progressively = true
share = false
# latestpostcount = 5
github = "whi-tw"
email = "hi@whi.tw"
linkedin = "tnwhitwell"
twitter = "whi_tw"
posts_navigation = true
githubRepo = "whi-tw/whi.tw/tree/master/src"

[params.utteranc]
enable = true
repo = "whi-tw/whi.tw"
issueTerm = "title"
